# Form implementation generated from reading ui file 'D:\PycharmProject\FinalProject\Project\ui_DBB\QSDBBMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(962, 571)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 961, 571))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAcceptDrops(True)
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\PycharmProject\\FinalProject\\Project\\ui_DBB\\../images/QSDBB.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_B = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_B.setGeometry(QtCore.QRect(290, 300, 471, 31))
        self.label_B.setText("")
        self.label_B.setObjectName("label_B")
        self.pushButton_D = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_D.setGeometry(QtCore.QRect(230, 400, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.pushButton_D.setFont(font)
        self.pushButton_D.setMouseTracking(False)
        self.pushButton_D.setTabletTracking(False)
        self.pushButton_D.setStyleSheet("QPushButton {\n"
"    font-weight: bold;\n"
"    background-color: rgb(162, 23, 23);\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D62828;\n"
"    color: yellow;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B02A2A;\n"
"}")
        self.pushButton_D.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_D.setObjectName("pushButton_D")
        self.pushButton_A = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_A.setGeometry(QtCore.QRect(230, 250, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_A.setFont(font)
        self.pushButton_A.setMouseTracking(False)
        self.pushButton_A.setTabletTracking(False)
        self.pushButton_A.setStyleSheet("QPushButton {\n"
"    font-weight: bold;\n"
"    background-color: rgb(162, 23, 23);\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D62828;\n"
"    color: yellow;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B02A2A;\n"
"}")
        self.pushButton_A.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_A.setObjectName("pushButton_A")
        self.pushButton_C = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_C.setGeometry(QtCore.QRect(230, 350, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_C.setFont(font)
        self.pushButton_C.setMouseTracking(False)
        self.pushButton_C.setTabletTracking(False)
        self.pushButton_C.setStyleSheet("QPushButton {\n"
"    font-weight: bold;\n"
"    background-color: rgb(162, 23, 23);\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D62828;\n"
"    color: yellow;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B02A2A;\n"
"}")
        self.pushButton_C.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_C.setObjectName("pushButton_C")
        self.label_C = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_C.setGeometry(QtCore.QRect(290, 360, 471, 31))
        self.label_C.setText("")
        self.label_C.setObjectName("label_C")
        self.label_D = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_D.setGeometry(QtCore.QRect(290, 410, 471, 31))
        self.label_D.setText("")
        self.label_D.setObjectName("label_D")
        self.label_Qs = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_Qs.setGeometry(QtCore.QRect(230, 190, 531, 41))
        self.label_Qs.setText("")
        self.label_Qs.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Qs.setWordWrap(True)
        self.label_Qs.setObjectName("label_Qs")
        self.pushButton_B = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_B.setGeometry(QtCore.QRect(230, 300, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_B.setFont(font)
        self.pushButton_B.setMouseTracking(False)
        self.pushButton_B.setTabletTracking(False)
        self.pushButton_B.setStyleSheet("QPushButton {\n"
"    font-weight: bold;\n"
"    background-color: rgb(162, 23, 23);\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D62828;\n"
"    color: yellow;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B02A2A;\n"
"}")
        self.pushButton_B.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_B.setObjectName("pushButton_B")
        self.label_A = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_A.setGeometry(QtCore.QRect(290, 250, 471, 31))
        self.label_A.setText("")
        self.label_A.setObjectName("label_A")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 962, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_D.setText(_translate("MainWindow", "D"))
        self.pushButton_A.setText(_translate("MainWindow", "A"))
        self.pushButton_C.setText(_translate("MainWindow", "C"))
        self.pushButton_B.setText(_translate("MainWindow", "B"))
