# Form implementation generated from reading ui file 'D:\PycharmProject\FinalProject\Project\ui\Correct.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(299, 543)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_Next = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Next.setGeometry(QtCore.QRect(-10, 430, 321, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Next.setFont(font)
        self.pushButton_Next.setMouseTracking(False)
        self.pushButton_Next.setTabletTracking(False)
        self.pushButton_Next.setStyleSheet("QPushButton {\n"
"    font-weight: bold;\n"
"    background-color: rgb(162, 23, 23);\n"
"    color: white;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D62828;\n"
"    color: yellow;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B02A2A;\n"
"}")
        self.pushButton_Next.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_Next.setObjectName("pushButton_Next")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 311, 51))
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 50, 312, 382))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 11, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("D:\\PycharmProject\\FinalProject\\Project\\ui\\../images/cards/bai_dinh.png"))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 299, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Next.setText(_translate("MainWindow", "Next"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#af0000;\">Chính Xác</span></p></body></html>"))
