# Form implementation generated from reading ui file 'D:\PycharmProject\FinalProject\Project\ui\LevelMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 540)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 5, 961, 501))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\PycharmProject\\FinalProject\\Project\\ui\\../images/level.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_Easy = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Easy.setGeometry(QtCore.QRect(320, 270, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Easy.setFont(font)
        self.pushButton_Easy.setMouseTracking(False)
        self.pushButton_Easy.setTabletTracking(False)
        self.pushButton_Easy.setStyleSheet("QPushButton {\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: rgb(83, 124, 62);\n"
"    border-radius: 15px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D62828;\n"
"    color: yellow;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B02A2A;\n"
"}")
        self.pushButton_Easy.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_Easy.setObjectName("pushButton_Easy")
        self.pushButton_Hard = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Hard.setGeometry(QtCore.QRect(490, 270, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Hard.setFont(font)
        self.pushButton_Hard.setMouseTracking(False)
        self.pushButton_Hard.setTabletTracking(False)
        self.pushButton_Hard.setStyleSheet("QPushButton {\n"
"    font-weight: bold;\n"
"    background-color: rgb(162, 23, 23);\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D62828;\n"
"    color: yellow;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B02A2A;\n"
"}")
        self.pushButton_Hard.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_Hard.setObjectName("pushButton_Hard")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 960, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Easy.setText(_translate("MainWindow", "Dễ"))
        self.pushButton_Hard.setText(_translate("MainWindow", "Khó"))
