# Form implementation generated from reading ui file 'D:\PycharmProject\FinalProject\Project\ui\SignInMainWinDow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 581)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 951, 551))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\PycharmProject\\FinalProject\\Project\\ui\\../images/DNDK.png"))
        self.label.setObjectName("label")
        self.pushButton_DangKy = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_DangKy.setGeometry(QtCore.QRect(420, 10, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_DangKy.setFont(font)
        self.pushButton_DangKy.setMouseTracking(False)
        self.pushButton_DangKy.setTabletTracking(False)
        self.pushButton_DangKy.setStyleSheet("QPushButton {\n"
"    font-weight: bold;\n"
"    background-color: rgb(162, 23, 23);\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D62828;\n"
"    color: yellow;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B02A2A;\n"
"}")
        self.pushButton_DangKy.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_DangKy.setObjectName("pushButton_DangKy")
        self.pushButton_DangNhap = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_DangNhap.setGeometry(QtCore.QRect(410, 280, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_DangNhap.setFont(font)
        self.pushButton_DangNhap.setMouseTracking(False)
        self.pushButton_DangNhap.setTabletTracking(False)
        self.pushButton_DangNhap.setStyleSheet("QPushButton {\n"
"    font-weight: bold;\n"
"    background-color: rgb(162, 23, 23);\n"
"    color: white;\n"
"    border-radius: 15px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D62828;\n"
"    color: yellow;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B02A2A;\n"
"}")
        self.pushButton_DangNhap.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_DangNhap.setObjectName("pushButton_DangNhap")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(210, 110, 201, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(210, 150, 201, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 190, 201, 31))
        self.label_4.setObjectName("label_4")
        self.lineEdit_DKusername = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_DKusername.setGeometry(QtCore.QRect(410, 111, 401, 31))
        self.lineEdit_DKusername.setStyleSheet("background-color: rgb(243, 240, 171);")
        self.lineEdit_DKusername.setObjectName("lineEdit_DKusername")
        self.lineEdit_DKpassword1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_DKpassword1.setGeometry(QtCore.QRect(410, 150, 401, 31))
        self.lineEdit_DKpassword1.setStyleSheet("background-color: rgb(243, 240, 171);")
        self.lineEdit_DKpassword1.setObjectName("lineEdit_DKpassword1")
        self.lineEdit_DKpassword2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_DKpassword2.setGeometry(QtCore.QRect(410, 190, 401, 31))
        self.lineEdit_DKpassword2.setStyleSheet("background-color: rgb(243, 240, 171);")
        self.lineEdit_DKpassword2.setObjectName("lineEdit_DKpassword2")
        self.lineEdit_DNpassword = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_DNpassword.setGeometry(QtCore.QRect(400, 420, 401, 31))
        self.lineEdit_DNpassword.setStyleSheet("background-color: rgb(243, 240, 171);")
        self.lineEdit_DNpassword.setObjectName("lineEdit_DNpassword")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 420, 201, 31))
        self.label_5.setObjectName("label_5")
        self.lineEdit_DNusername = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_DNusername.setGeometry(QtCore.QRect(400, 381, 401, 31))
        self.lineEdit_DNusername.setStyleSheet("background-color: rgb(243, 240, 171);")
        self.lineEdit_DNusername.setObjectName("lineEdit_DNusername")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 380, 201, 31))
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 953, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_DangKy.setText(_translate("MainWindow", "Đăng ký"))
        self.pushButton_DangNhap.setText(_translate("MainWindow", "Đăng nhập"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Tên người dùng:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Mật khẩu:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Nhập lại mật khẩu:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Mật khẩu:</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Tên người dùng:</span></p></body></html>"))
