# Form implementation generated from reading ui file 'D:\PycharmProject\FinalProject\Project\ui\TBB_HT.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(271, 143)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 271, 91))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("D:\\PycharmProject\\FinalProject\\Project\\ui\\../images/TBB_HT.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton_Next = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Next.setGeometry(QtCore.QRect(90, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Next.setFont(font)
        self.pushButton_Next.setMouseTracking(False)
        self.pushButton_Next.setTabletTracking(False)
        self.pushButton_Next.setStyleSheet("QPushButton {\n"
"    font-weight: bold;\n"
"    color: white;\n"
"    background-color: rgb(226, 229, 185);\n"
"    border-radius: 20px;\n"
"    border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #D62828;\n"
"    color: yellow;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #B02A2A;\n"
"}")
        self.pushButton_Next.setIconSize(QtCore.QSize(90, 90))
        self.pushButton_Next.setObjectName("pushButton_Next")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 271, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Next.setText(_translate("MainWindow", "Next"))
