# Form implementation generated from reading ui file 'D:\PycharmProject\FinalProject\Project\ui\Top10MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(974, 571)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bglabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.bglabel.setGeometry(QtCore.QRect(0, 0, 961, 511))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bglabel.sizePolicy().hasHeightForWidth())
        self.bglabel.setSizePolicy(sizePolicy)
        self.bglabel.setAcceptDrops(True)
        self.bglabel.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.bglabel.setText("")
        self.bglabel.setPixmap(QtGui.QPixmap("D:\\PycharmProject\\FinalProject\\Project\\ui\\../images/TOP10.png"))
        self.bglabel.setScaledContents(True)
        self.bglabel.setObjectName("bglabel")
        self.back = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back.setGeometry(QtCore.QRect(390, 470, 181, 36))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setStyleSheet("background-color: rgb(162, 23, 23);\n"
"color: rgb(255, 255, 255);")
        self.back.setObjectName("back")
        self.tabletop10 = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tabletop10.setGeometry(QtCore.QRect(50, 130, 871, 331))
        self.tabletop10.setStyleSheet("QTableWidget {\n"
"    background-color: #fff8dc;\n"
"    alternate-background-color: #fceeb5;\n"
"    font-size: 16px;\n"
"    color: #333;\n"
"    border: 2px solid #d4a017;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #ffcc66;\n"
"    color: #5e3c00;\n"
"    font-size: 25px;\n"
"    font-weight: bold;\n"
"    padding: 8px;\n"
"    border: 1px solid #d4a017;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    qproperty-textAlignment: \'AlignCenter\';\n"
"}\n"
"")
        self.tabletop10.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tabletop10.setAlternatingRowColors(True)
        self.tabletop10.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tabletop10.setRowCount(10)
        self.tabletop10.setObjectName("tabletop10")
        self.tabletop10.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.tabletop10.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.tabletop10.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(20)
        item.setFont(font)
        self.tabletop10.setHorizontalHeaderItem(2, item)
        self.tabletop10.horizontalHeader().setCascadingSectionResizes(True)
        self.tabletop10.horizontalHeader().setDefaultSectionSize(273)
        self.tabletop10.horizontalHeader().setMinimumSectionSize(100)
        self.tabletop10.horizontalHeader().setSortIndicatorShown(False)
        self.tabletop10.horizontalHeader().setStretchLastSection(True)
        self.tabletop10.verticalHeader().setVisible(False)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 974, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.back.setText(_translate("MainWindow", "<-- Quay lại"))
        item = self.tabletop10.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Thứ hạng"))
        item = self.tabletop10.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên người chơi"))
        item = self.tabletop10.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Tổng điểm số"))
